version: 2.1
jobs:
  build_and_test:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - run: 
          name: Install
          command: npm install
      - run:
          name: Running Build
          command: npm run build
      - run:
          name: Running Tests
          command: npm run test
  build_and_release: 
    macos:
      xcode: 11.3.0
    steps:
      - run: 
          name: Install
          command: npm install
      - run:
          name: Running Build
          command: npm run build
      - run:
          name: Running Release
          command: npm run semantic-release
workflows:
  version: 2
  branch_builds:
    jobs:
      - build_and_test
  release:
    jobs:
      - build_and_release
        filters:
          branches:
            only: master